import '../../domain/entities/book.dart';

final List<Book> mockBooks = [
  Book(
    id: '1',
    title: 'Dədə Qorqud',
    author: 'Naməlum',
    category: 'Klassik',
    categoryName: 'Klassik',
    price: 12.99,
    currency: 'AZN',
    imageUrl: 'https://covers.openlibrary.org/b/id/8091016-L.jpg',
    description: '"Kitabi-Dədə Qorqud" Azərbaycan və türk xalq ədəbiyyatının ən qədim dastanlarından biridir.',
    publisher: 'Şərq-Qərb',
    stock: 10, isbn: '', pageCount: 300, language: 'az',
    publishedYear: 2019, rating: 4.8, reviewCount: 120, isFavorited: false,
  ),
  Book(
    id: '2',
    title: 'Ali və Nino',
    author: 'Kurban Said',
    category: 'Roman',
    categoryName: 'Roman',
    price: 15.99,
    currency: 'AZN',
    imageUrl: 'https://covers.openlibrary.org/b/id/8739161-L.jpg',
    description: 'Şərq və Qərb mədəniyyətləri arasında qalan iki gəncin sevgi hekayəsi.',
    publisher: 'Qanun',
    stock: 5, isbn: '', pageCount: 280, language: 'az',
    publishedYear: 2019, rating: 4.9, reviewCount: 250, isFavorited: false,
  ),
  Book(
    id: '3',
    title: 'Əliqulu Qəmküsar',
    author: 'Mirzə Cəlil',
    category: 'Hekayə',
    categoryName: 'Hekayə',
    price: 8.99,
    currency: 'AZN',
    imageUrl: 'https://covers.openlibrary.org/b/id/10527843-L.jpg',
    description: 'Mirzə Cəlilin satirik və düşündürücü hekayələrindən ibarət kitabdır.',
    publisher: 'Elm',
    stock: 15, isbn: '', pageCount: 150, language: 'az',
    publishedYear: 2021, rating: 4.5, reviewCount: 80, isFavorited: false,
  ),
  Book(
    id: '4',
    title: 'Ölülər',
    author: 'Mirzə Cəlil',
    category: 'Dram',
    categoryName: 'Dram',
    price: 10.99,
    currency: 'AZN',
    imageUrl: 'https://covers.openlibrary.org/b/id/9255566-L.jpg',
    description: 'Cəmiyyətdəki savadsızlığı və fanatizmi kəskin satira ilə tənqid edən tragikomik dramdır.',
    publisher: 'Elm',
    stock: 8, isbn: '', pageCount: 120, language: 'az',
    publishedYear: 2018, rating: 4.7, reviewCount: 95, isFavorited: false,
  ),
  Book(
    id: '5',
    title: 'Dumanlı Təbriz',
    author: 'Məmməd Səid Ordubadi',
    category: 'Roman',
    categoryName: 'Roman',
    price: 14.99,
    currency: 'AZN',
    imageUrl: 'https://covers.openlibrary.org/b/id/8231432-L.jpg',
    description: 'Cənubi Azərbaycanın ictimai və siyasi həyatını əks etdirən tarixi roman.',
    publisher: 'Azərnəşr',
    stock: 6, isbn: '', pageCount: 400, language: 'az',
    publishedYear: 2017, rating: 4.6, reviewCount: 60, isFavorited: false,
  ),
  Book(
    id: '6',
    title: 'Hophopnamə',
    author: 'Sabir',
    category: 'Şeir',
    categoryName: 'Şeir',
    price: 9.99,
    currency: 'AZN',
    imageUrl: 'https://covers.openlibrary.org/b/id/7887482-L.jpg',
    description: 'Sabirin satirik şeirlərindən ibarət məşhur əsərdir.',
    publisher: 'Şərq-Qərb',
    stock: 20, isbn: '', pageCount: 200, language: 'az',
    publishedYear: 2022, rating: 4.7, reviewCount: 110, isFavorited: false,
  ),
  Book(
    id: '7',
    title: 'Anamın Kitabı',
    author: 'Cəlil Məmmədquluzadə',
    category: 'Dram',
    categoryName: 'Dram',
    price: 11.99,
    currency: 'AZN',
    imageUrl: 'https://covers.openlibrary.org/b/id/8974532-L.jpg',
    description: 'Milli kimlik və ailə münasibətlərini əks etdirən klassik dram əsəridir.',
    publisher: 'Elm',
    stock: 12, isbn: '', pageCount: 180, language: 'az',
    publishedYear: 2019, rating: 4.6, reviewCount: 75, isFavorited: false,
  ),
  Book(
    id: '8',
    title: 'Müsibəti Fəxrəddin',
    author: 'Rəşid bəy Əfəndiyev',
    category: 'Roman',
    categoryName: 'Roman',
    price: 13.99,
    currency: 'AZN',
    imageUrl: 'https://covers.openlibrary.org/b/id/9318874-L.jpg',
    description: 'Maarifçilik ideyalarını ön plana çıxaran təsirli Azərbaycan romanıdır.',
    publisher: 'Qanun',
    stock: 7, isbn: '', pageCount: 250, language: 'az',
    publishedYear: 2020, rating: 4.4, reviewCount: 50, isFavorited: false,
  ),
  Book(
    id: '9',
    title: 'Aldanmış Kəvakib',
    author: 'Mirzə Fətəli Axundzadə',
    category: 'Hekayə',
    categoryName: 'Hekayə',
    price: 7.99,
    currency: 'AZN',
    imageUrl: 'https://covers.openlibrary.org/b/id/8074254-L.jpg',
    description: 'İnsan münasibətlərini və cəmiyyətin nöqsanlarını maraqlı süjetlə təqdim edir.',
    publisher: 'Azərnəşr',
    stock: 9, isbn: '', pageCount: 130, language: 'az',
    publishedYear: 2016, rating: 4.3, reviewCount: 45, isFavorited: false,
  ),
  Book(
    id: '10',
    title: 'Səməd Vurğun Seçilmiş Əsərləri',
    author: 'Səməd Vurğun',
    category: 'Şeir',
    categoryName: 'Şeir',
    price: 16.99,
    currency: 'AZN',
    imageUrl: 'https://covers.openlibrary.org/b/id/9780689-L.jpg',
    description: 'Xalq şairi Səməd Vurğunun ən məşhur şeirləri və poemalarının toplusu.',
    publisher: 'Şərq-Qərb',
    stock: 18, isbn: '', pageCount: 320, language: 'az',
    publishedYear: 2023, rating: 4.9, reviewCount: 200, isFavorited: false,
  ),
  Book(
    id: '11',
    title: 'Sapiens',
    author: 'Yuval Noah Harari',
    category: 'Elmi',
    categoryName: 'Elmi',
    price: 22.99,
    currency: 'AZN',
    imageUrl: 'https://covers.openlibrary.org/b/id/8739941-L.jpg',
    description: 'Bəşəriyyətin yaranışından müasir dövrə qədər keçdiyi inkişaf yolunu izah edir.',
    publisher: 'Harper',
    stock: 25, isbn: '9780062316097', pageCount: 443, language: 'az',
    publishedYear: 2021, rating: 4.8, reviewCount: 500, isFavorited: false,
  ),
  Book(
    id: '12',
    title: 'Atomik Vərdişlər',
    author: 'James Clear',
    category: 'Qeyri-bədii',
    categoryName: 'Qeyri-bədii',
    price: 18.99,
    currency: 'AZN',
    imageUrl: 'https://covers.openlibrary.org/b/id/10410790-L.jpg',
    description: 'Kiçik vərdişlərin böyük nəticələr verdiyini izah edən şəxsi inkişaf kitabı.',
    publisher: 'Collins',
    stock: 30, isbn: '9780735211292', pageCount: 320, language: 'az',
    publishedYear: 2022, rating: 4.9, reviewCount: 600, isFavorited: false,
  ),
  Book(
    id: '13',
    title: 'Kiçik Şahzadə',
    author: 'Antoine de Saint-Exupéry',
    category: 'Uşaq',
    categoryName: 'Uşaq',
    price: 9.99,
    currency: 'AZN',
    imageUrl: 'https://covers.openlibrary.org/b/id/8406786-L.jpg',
    description: 'Dostluq, sevgi və insan münasibətləri haqqında dərin mesajlar verən məşhur roman.',
    publisher: 'Qanun',
    stock: 22, isbn: '', pageCount: 96, language: 'az',
    publishedYear: 2019, rating: 4.9, reviewCount: 800, isFavorited: false,
  ),
  Book(
    id: '14',
    title: 'Harry Potter və Fəlsəfə Daşı',
    author: 'J.K. Rowling',
    category: 'Uşaq',
    categoryName: 'Uşaq',
    price: 19.99,
    currency: 'AZN',
    imageUrl: 'https://covers.openlibrary.org/b/id/10110415-L.jpg',
    description: 'Harry Potterin sehrli Hogwarts məktəbində başlayan macərasının ilk hissəsi.',
    publisher: 'Bloomsbury',
    stock: 15, isbn: '9780747532699', pageCount: 332, language: 'az',
    publishedYear: 2020, rating: 4.9, reviewCount: 1200, isFavorited: false,
  ),
  Book(
    id: '15',
    title: 'Zamanın Qısa Tarixi',
    author: 'Stephen Hawking',
    category: 'Elmi',
    categoryName: 'Elmi',
    price: 20.99,
    currency: 'AZN',
    imageUrl: 'https://covers.openlibrary.org/b/id/8084956-L.jpg',
    description: 'Kainat, qara dəliklər və zaman anlayışını sadə dildə izah edən elmi kitab.',
    publisher: 'Bantam',
    stock: 11, isbn: '9780553380163', pageCount: 212, language: 'az',
    publishedYear: 2021, rating: 4.7, reviewCount: 350, isFavorited: false,
  ),
  Book(
    id: '16',
    title: '1984',
    author: 'George Orwell',
    category: 'Roman',
    categoryName: 'Roman',
    price: 14.99,
    currency: 'AZN',
    imageUrl: 'https://covers.openlibrary.org/b/id/8575708-L.jpg',
    description: 'Totalitar idarəetmə və insan azadlığının məhdudlaşdırılması haqqında distopik roman.',
    publisher: 'Secker',
    stock: 14, isbn: '9780451524935', pageCount: 328, language: 'az',
    publishedYear: 2018, rating: 4.8, reviewCount: 900, isFavorited: false,
  ),
  Book(
    id: '17',
    title: 'Cinayət və Cəza',
    author: 'Fyodor Dostoyevski',
    category: 'Klassik',
    categoryName: 'Klassik',
    price: 17.99,
    currency: 'AZN',
    imageUrl: 'https://covers.openlibrary.org/b/id/8091037-L.jpg',
    description: 'Cinayət, vicdan əzabı və insan psixologiyasını dərindən araşdıran şah əsər.',
    publisher: 'Penguin',
    stock: 10, isbn: '9780143058144', pageCount: 545, language: 'az',
    publishedYear: 2020, rating: 4.8, reviewCount: 700, isFavorited: false,
  ),
  Book(
    id: '18',
    title: 'Düşün və Var Ol',
    author: 'Napoleon Hill',
    category: 'Qeyri-bədii',
    categoryName: 'Qeyri-bədii',
    price: 13.99,
    currency: 'AZN',
    imageUrl: 'https://covers.openlibrary.org/b/id/9255566-L.jpg',
    description: 'Uğur qazanmaq üçün düşüncə tərzinin vacibliyini izah edən motivasiya kitabı.',
    publisher: 'Litera',
    stock: 20, isbn: '', pageCount: 238, language: 'az',
    publishedYear: 2019, rating: 4.5, reviewCount: 280, isFavorited: false,
  ),
  Book(
    id: '19',
    title: 'Məhəbbət və Ölüm',
    author: 'İlyas Əfəndiyev',
    category: 'Dram',
    categoryName: 'Dram',
    price: 11.99,
    currency: 'AZN',
    imageUrl: 'https://covers.openlibrary.org/b/id/9318800-L.jpg',
    description: 'Sevgi, insan münasibətləri və həyatın çətinliklərini təsvir edən dram əsəri.',
    publisher: 'Elm',
    stock: 8, isbn: '', pageCount: 160, language: 'az',
    publishedYear: 2021, rating: 4.5, reviewCount: 65, isFavorited: false,
  ),
  Book(
    id: '20',
    title: 'Şirvanlı Qız',
    author: 'Süleyman Sani Axundov',
    category: 'Hekayə',
    categoryName: 'Hekayə',
    price: 8.99,
    currency: 'AZN',
    imageUrl: 'https://covers.openlibrary.org/b/id/8406750-L.jpg',
    description: 'Azərbaycan həyatını və insan münasibətlərini əks etdirən hekayələr toplusu.',
    publisher: 'Azərnəşr',
    stock: 13, isbn: '', pageCount: 175, language: 'az',
    publishedYear: 2017, rating: 4.3, reviewCount: 40, isFavorited: false,
  ),
];